app/models.py
from . import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    password_hash = db.Column(db.String(255))
    pitches = db.relationship('Pitch',backref = 'user',lazy = "dynamic")
    comments = db.relationship('Comment',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return f'{self.username}'


class Pitch(db.Model):
    __tablename__ = 'pitches'
    id = db.Column(db.Integer,primary_key = True)
    pitch_title=db.Column(db.String)
    pitch_text=db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    category = db.Column(db.String)
    upvotes = db.Column(db.Integer)
    downvotes = db.Column(db.Integer)
    comments = db.relationship('Comment',backref = 'pitch',lazy = "dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    
    def __repr__(self):
        return f'{self.pitch_title}'


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
    comment_text=db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    
    def __repr__(self):
        return f'{self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import Required


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Write a bio.',validators = [Required()])
    submit = SubmitField('Submit')


class PitchesForm(FlaskForm):
    title = StringField('Pitch title',validators=[Required()])
    pitch = TextAreaField('Your pitch', validators=[Required()],render_kw={'class': 'form-control', 'rows': 10})
    category_opts = RadioField('Choose category', validators=[Required()], choices=[('pickup','Pickup pitch'),('interview','Interview pitch'),('product','Product pitch'),('promotion','Promotion pitch'),('idea','Idea pitch')])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = StringField('Write comment.',validators = [Required()])
    submit = SubmitField('Post')

class UpvoteForm(FlaskForm):
    upvote=SubmitField('Upvote')

class DownvoteForm(FlaskForm):
    downvote=SubmitField('Downvote')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    # Creating app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from flask_login import login_required,current_user
from ..models import User,Pitch,Comment
from .forms import UpdateProfile,PitchesForm,CommentForm,UpvoteForm,DownvoteForm
from .. import db


@main.route('/')
def index():
    pitches=Pitch.query.order_by(Pitch.posted.desc())
    top_pitch=Pitch.query.order_by(Pitch.upvotes.desc()).first()        
    return render_template('index.html', pitches=pitches, top_pitch=top_pitch)


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    pitches=Pitch.query.filter_by(user_id=user.id).order_by(Pitch.posted.desc())
    top_pitch=Pitch.query.order_by(Pitch.upvotes.desc()).first()  

    return render_template("profile/profile.html", user = user, pitches=pitches, top_pitch=top_pitch)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    pitches=Pitch.query.filter_by(user_id=user.id).order_by(Pitch.posted.desc())
    top_pitch=Pitch.query.order_by(Pitch.upvotes.desc()).first()  

    return render_template('profile/update.html',form =form, user=user, pitches=pitches, top_pitch=top_pitch)



@main.route('/new-pitch', methods = ['GET','POST'])
@login_required
def new_pitch():
    form = PitchesForm()    
    if form.validate_on_submit():
        title = form.title.data
        pitch = form.pitch.data
        category = form.category_opts.data
        upvote=0
        downvote=0       

        # Updated pitch instance
        this_pitch = Pitch(pitch_title=title, pitch_text=pitch, category=category, upvotes=upvote, downvotes=downvote, user=current_user)

        # save pitch method
        this_pitch.save_pitch()
        return redirect(url_for('.index'))

    top_pitch=Pitch.query.order_by(Pitch.upvotes.desc()).first()    
    title = 'New Pitch'
    return render_template('new_pitch.html',title = title, pitch_form=form, top_pitch=top_pitch)


@main.route('/pitch/category/<cat>')
def category(cat):
    pitches=Pitch.query.filter_by(category=cat).order_by(Pitch.posted.desc()) 
    top_pitch=Pitch.query.order_by(Pitch.upvotes.desc()).first()    
    title=pitches[0].category.capitalize()
    return render_template('category.html', title=title, pitches=pitches, top_pitch=top_pitch)



@main.route('/pitch/comment/<pitch_id>',methods = ['GET','POST'])
@login_required
def comment(pitch_id):
    pitch=Pitch.query.filter_by(id=pitch_id).first()
    form = CommentForm()
    form1=UpvoteForm()
    form2=DownvoteForm()   
    if form.validate_on_submit():
        new_comment = form.comment.data             

        # Updated comment instance
        this_comment = Comment(comment_text=new_comment,pitch=pitch, user=current_user)

        # save comment method
        this_comment.save_comment()
        return redirect(url_for('.comment', pitch_id=pitch_id))

    if form1.validate_on_submit() and form1.upvote.data:
        pitch.upvotes+=1
        db.session.commit()
        return redirect(url_for('.comment', pitch_id=pitch_id))

    elif form2.validate_on_submit() and form2.downvote.data:
        pitch.downvotes+=1
        db.session.commit()
        return redirect(url_for('.comment', pitch_id=pitch_id))

    top_pitch=Pitch.query.order_by(Pitch.upvotes.desc()).first()  
    comments=Comment.query.filter_by(pitch_id=pitch_id).order_by(Comment.posted.desc())  
    title = pitch.pitch_title
    return render_template('new_comment.html',title = title, comments=comments, comment_form=form, pitch=pitch, upvote_form=form1, downvote_form=form2, top_pitch=top_pitch)
    

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}

{% block scripts%}
    {{ super() }}    
    <script src="{{url_for('static',filename='js/scripts.js')}}"></script>
{% endblock %}

{% block head%}
    {{ super() }}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- <script src="js/bootstrap.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="  crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
{% endblock %}

{% block title%}
    {{ super() }}    

    {% if title %}
        
    {% else %}
        standOUT
    {% endif %}
    

{% endblock %}

app/templates/category.html
{% extends 'base.html' %}

{% import 'macros.html' as macro%}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <!--Sidenav-->
        <div class="col-xs-12 col-md-3">
            <div class="jumbotron jumbotron1">
                <div class="row border-b">
                    <div class="col-xs-12 brand">
                        <a href="/">
                            <h1>stand</h1>
                            <h1>OUT</h1>
                        </a>
                        <h3 class="text-right">- a minute's pitch</h3>
                    </div>
                </div>                
                <div class="row">
                    <div class="col-xs-12">
                        <p><a href="/">Latest pitches</a></p>
                        <hr>
                    </div>
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <p>Categories</p>
                            </div>                            
                            <div class="col-xs-12">
                                <div class="row lists">
                                    <div class="col-xs-2"></div>
                                    <div class="col-xs-10">
                                        <p><a href="{{url_for('main.category',cat='pickup')}}">Pickup lines</a></p>
                                        <p><a href="{{url_for('main.category',cat='interview')}}">Interview pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='product')}}">Product pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='promotion')}}">Promotion pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='idea')}}">Idea pitch</a></p>                                         
                                    </div>
                                </div>
                            </div>
                        </div>                                               
                        <hr>
                    </div>
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <p><a href="{{url_for('main.new_pitch')}}">Submit pitch</a></p>
                            </div>                           
                        </div>                                               
                        <hr>
                    </div>                    
                </div>
            </div>
        </div>

        <!--Content section-->
        <div class="col-xs-12 col-md-6">
            <div class="jumbotron jumbotron2">                
                <div class="row display-flex">
                    <div class="col-xs-12 border-b">
                        <h2>{{title}} pitch</h2>
                    </div>

                    {{ macro.displayPitchesCategory(pitches) }}
                                                        
                </div>
            </div>
        </div>

        <!--right column section-->
        <div class="col-xs-12 col-md-3">
            <div class="jumbotron jumbotron3">

                {% if current_user.is_authenticated %}                    
                    <h3>{{current_user.username| capitalize}}</h3>
                    <p class="text-muted"><a href="{{url_for('main.profile',uname=current_user.username)}}">View profile</a></p>
                    <a href="{{url_for('auth.logout')}}"><button class="btn btn-primary">Sign out</button></a>                    
                {% else %}
                    <a href="{{url_for('auth.login')}}"><button class="btn btn-primary">Sign in</button></a>                    
                {%endif%}
                
            </div>
            <div class="jumbotron jumbotron4">
                <div class="row">
                    <div class="col-xs-12">
                        <h2>Top Pitch</h2>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{top_pitch.pitch_title | upper}}</h4>
                                <h5 class="card-subtitle mb-2 text-muted">{{top_pitch.category | upper}} PITCH</h5>
                                <h5 class="card-subtitle mb-2 text-muted">{{top_pitch.posted.strftime("%d %b %Y %I:%M %p")}}</h5>
                                <p class="card-text">{{top_pitch.pitch_text}}</p>
                                <p>Posted by: {{top_pitch.user}}</p>
                                <div class="row">
                                    <div class="col-xs-1 text-right">
                                        <span class="glyphicon glyphicon-thumbs-up"></span>
                                    </div>
                                    <div class="col-xs-1">
                                        <p>{{top_pitch.upvotes}}</p>
                                    </div>
                                    <div class="col-xs-1 text-right">
                                        <span class="glyphicon glyphicon-thumbs-down"></span>
                                    </div>
                                    <div class="col-xs-1">
                                        <p>{{top_pitch.downvotes}}</p>
                                    </div>
                                </div>
                                <p class="text-muted"><a href="{{url_for('main.comment',pitch_id=top_pitch.id)}}">Comments & Votes</a></p>                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
        
    </div>
</div>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="jumbotron text-center">
                <h1>404 Error</h1>
                <h1>Page Not Found</h1>
                <button class="btn btn-outline-secondary"><a href="/">Home Page</a></button>
            </div>
        </div>
    </div>
</div>    

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% import 'macros.html' as macro%}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <!--Sidenav-->
        <div class="col-xs-12 col-md-3">
            <div class="jumbotron jumbotron1">
                <div class="row border-b">
                    <div class="col-xs-12 brand">
                        <a href="/">
                            <h1>stand</h1>
                            <h1>OUT</h1>
                        </a>
                        <h3 class="text-right">- a minute's pitch</h3>
                    </div>
                </div>                
                <div class="row">
                    <div class="col-xs-12">
                        <p><a href="/">Latest pitches</a></p>
                        <hr>
                    </div>
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <p>Categories</p>
                            </div>                            
                            <div class="col-xs-12">
                                <div class="row lists">
                                    <div class="col-xs-2"></div>
                                    <div class="col-xs-10">
                                        <p><a href="{{url_for('main.category',cat='pickup')}}">Pickup lines</a></p>
                                        <p><a href="{{url_for('main.category',cat='interview')}}">Interview pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='product')}}">Product pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='promotion')}}">Promotion pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='idea')}}">Idea pitch</a></p>                                         
                                    </div>
                                </div>
                            </div>
                        </div>                                               
                        <hr>
                    </div>
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <p><a href="{{url_for('main.new_pitch')}}">Submit pitch</a></p>
                            </div>                           
                        </div>                                               
                        <hr>
                    </div>                    
                </div>
            </div>
        </div>

        <!--Content section-->
        <div class="col-xs-12 col-md-6">
            <div class="jumbotron jumbotron2">                
                <div class="row display-flex">
                    <div class="col-xs-12 border-b">
                        <h2 class="pitch-head">Pitches</h2>
                    </div>

                    {{ macro.displayPitchesHome(pitches) }}
                                                        
                </div>
            </div>
        </div>

        <!--right column section-->
        <div class="col-xs-12 col-md-3">
            <div class="jumbotron jumbotron3">

                {% if current_user.is_authenticated %}                    
                    <h3>{{current_user.username| capitalize}}</h3>
                    <p class="text-muted"><a href="{{url_for('main.profile',uname=current_user.username)}}">View profile</a></p>
                    <a href="{{url_for('auth.logout')}}"><button class="btn btn-primary">Sign out</button></a>                    
                {% else %}
                    <h3>Have an account?</h3>
                    <a href="{{url_for('auth.login')}}"><button class="btn btn-primary">Sign in</button></a>                    
                {%endif%}
                
            </div>
            <div class="jumbotron jumbotron4">
                <div class="row">
                    <div class="col-xs-12">
                        <h2>Top Pitch</h2>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{top_pitch.pitch_title | upper}}</h4>
                                <h5 class="card-subtitle mb-2 text-muted">{{top_pitch.category | upper}} PITCH</h5>
                                <h5 class="card-subtitle mb-2 text-muted">{{top_pitch.posted.strftime("%d %b %Y %I:%M %p")}}</h5>
                                <p class="card-text">{{top_pitch.pitch_text}}</p>
                                <p>Posted by: {{top_pitch.user}}</p>
                                <div class="row">
                                    <div class="col-xs-1 text-right">
                                        <span class="glyphicon glyphicon-thumbs-up"></span>
                                    </div>
                                    <div class="col-xs-1">
                                        <p>{{top_pitch.upvotes}}</p>
                                    </div>
                                    <div class="col-xs-1 text-right">
                                        <span class="glyphicon glyphicon-thumbs-down"></span>
                                    </div>
                                    <div class="col-xs-1">
                                        <p>{{top_pitch.downvotes}}</p>
                                    </div>
                                </div>
                                <p class="text-muted"><a href="{{url_for('main.comment',pitch_id=top_pitch.id)}}">Comments & Votes</a></p>                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
        
    </div>
</div>

{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% import 'macros.html' as macro%}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <!--Sidenav-->
        <div class="col-xs-12 col-md-3">
            <div class="jumbotron jumbotron1">
                <div class="row border-b">
                    <div class="col-xs-12 brand">
                        <a href="/">
                            <h1>stand</h1>
                            <h1>OUT</h1>
                        </a>
                        <h3 class="text-right">- a minute's pitch</h3>
                    </div>
                </div>                
                <div class="row">
                    <div class="col-xs-12">
                        <p><a href="/">Latest pitches</a></p>
                        <hr>
                    </div>
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <p>Categories</p>
                            </div>                            
                            <div class="col-xs-12">
                                <div class="row lists">
                                    <div class="col-xs-2"></div>
                                    <div class="col-xs-10">
                                        <p><a href="{{url_for('main.category',cat='pickup')}}">Pickup lines</a></p>
                                        <p><a href="{{url_for('main.category',cat='interview')}}">Interview pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='product')}}">Product pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='promotion')}}">Promotion pitch</a></p>
                                        <p><a href="{{url_for('main.category',cat='idea')}}">Idea pitch</a></p>                                         
                                    </div>
                                </div>
                            </div>
                        </div>                                               
                        <hr>
                    </div>
                    <div class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-12">
                                <p><a href="{{url_for('main.new_pitch')}}">Submit pitch</a></p>
                            </div>                           
                        </div>                                               
                        <hr>
                    </div>                    
                </div>
            </div>
        </div>

        <!--Content section-->
        <div class="col-xs-12 col-md-6">
            <div class="jumbotron jumbotron2">                
                <div class="row">
                    <div class="col-xs-12 border-b">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{pitch.pitch_title | upper}}</h4>
                                <h5 class="card-subtitle mb-2 text-muted">{{pitch.category | upper}} PITCH</h5>                    
                                <h5 class="card-subtitle mb-2 text-muted">{{pitch.posted.strftime("%d %b %Y %I:%M %p")}}</h5>
                                <p class="card-text">{{pitch.pitch_text}}</p>
                                <p>Posted by: {{pitch.user}}</p>
                                <div class="row padding">
                                    <div class="col-xs-2 text-right">
                                        {{ wtf.quick_form(upvote_form) }}
                                    </div>
                                    <div class="col-xs-2 text-left">
                                        <button class="btn btn-primary">{{ pitch.upvotes }}</button>                                        
                                    </div>
                                    <div class="col-xs-2 text-right">
                                        {{ wtf.quick_form(downvote_form) }}
                                    </div>
                                    <div class="col-xs-2 text-left">
                                        <button class="btn btn-danger">{{ pitch.downvotes }}</button>
                                    </div>
                                </div>                    
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12">
                        {{ wtf.quick_form(comment_form) }}        
                    </div><br>
                    {{macro.displayComments(comments)}}
                </div>
            </div>
        </div>

        <!--right column section-->
        <div class="col-xs-12 col-md-3">
            <div class="jumbotron jumbotron3">

                {% if current_user.is_authenticated %}                    
                    <h3>{{current_user.username| capitalize}}</h3>
                    <p class="text-muted"><a href="{{url_for('main.profile',uname=current_user.username)}}">View profile</a></p>
                    <a href="{{url_for('auth.logout')}}"><button class="btn btn-primary">Sign out</button></a>                    
                {% else %}
                    <a href="{{url_for('auth.login')}}"><button class="btn btn-primary">Sign in</button></a>                    
                {%endif%}
                
            </div>
            <div class="jumbotron jumbotron4">
                <div class="row">
                    <div class="col-xs-12">
                        <h2>Top Pitch</h2>
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{top_pitch.pitch_title | upper}}</h4>
                                <h5 class="card-subtitle mb-2 text-muted">{{top_pitch.category | upper}} PITCH</h5>
                                <h5 class="card-subtitle mb-2 text-muted">{{top_pitch.posted.strftime("%d %b %Y %I:%M %p")}}</h5>
                                <p class="card-text">{{top_pitch.pitch_text}}</p>
                                <p>Posted by: {{top_pitch.user}}</p>
                                <div class="row">
                                    <div class="col-xs-1 text-right">
                                        <span class="glyphicon glyphicon-thumbs-up"></span>
                                    </div>
                                    <div class="col-xs-1">
                                        <p>{{top_pitch.upvotes}}</p>
                                    </div>
                                    <div class="col-xs-1 text-right">
                                        <span class="glyphicon glyphicon-thumbs-down"></span>
                                    </div>
                                    <div class="col-xs-1">
                                        <p>{{top_pitch.downvotes}}</p>
                                    </div>
                                </div>
                                <p class="text-muted"><a href="{{url_for('main.comment',pitch_id=top_pitch.id)}}">Comments & Votes</a></p>                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        
        
    </div>
</div>

{% endblock %}